In [7]:
from numpy import random

In [13]:
array1 = random.randint(0,100,10)
array2 = random.randint(0,100,10)
array3 = random.randint(0,100,10)

In [14]:
array1, array2, array3

(array([ 5, 17, 70, 37, 43, 81, 98, 91, 99, 97]),
 array([21, 54, 48, 98, 98, 20, 12, 23, 52, 99]),
 array([85, 77, 17, 79, 97, 94, 25, 40, 89, 81]))

In [15]:
array3[3]

79

In [16]:
if coworkers_went_into_anaphylaxis_eating_here == True:
    if the_food >= good_enough_to_risk_it:
        print("YOLO. Get your EpiPens ready")
    else:
        print("Let's eat somewhere else")
        
elif ((insects in menu) or (exotic_meat in menu)):
    if tried_it_before == True and it_was_good == True:
        print("Chow down and don't tell anyone what you ate")
    else:
        print("Don't order the silkworms/grasshoppers/dolphin")
        
else:
    print("I'm ordering room service or going to McDonalds")
        

NameError: name 'coworkers_went_into_anaphylaxis_eating_here' is not defined

In [17]:
"Don't order the silkworms/grasshoppers/dolphin"

"Don't order the silkworms/grasshoppers/dolphin"