In [7]:
from numpy import random

In [13]:
array1 = random.randint(0,100,10)
array2 = random.randint(0,100,10)
array3 = random.randint(0,100,10)

In [14]:
array1, array2, array3

(array([ 5, 17, 70, 37, 43, 81, 98, 91, 99, 97]),
 array([21, 54, 48, 98, 98, 20, 12, 23, 52, 99]),
 array([85, 77, 17, 79, 97, 94, 25, 40, 89, 81]))

In [36]:
def sum_of_arrays(array1,array2,array3):
    element_list1 = []
    element_list2 = []
    element_list3 = []
    
    while len(element_list1) < 3:
        element_list1.append(int(input('Select an index # (0-9) from the first array: ')))
    print() 
    
    while len(element_list2) < 3:
        element_list2.append(int(input('Select an index # (0-9) from the second array: ')))
    print()
    
    while len(element_list3) < 3:
        element_list3.append(int(input('Select an index # (0-9) from the third array: ')))
    print()
    
    array1_sum = array1[element_list1[0]] + array1[element_list1[1]] + array1[element_list1[2]]
    array2_sum = array2[element_list2[0]] + array2[element_list2[1]] + array2[element_list2[2]]
    array3_sum = array3[element_list3[0]] + array3[element_list3[1]] + array3[element_list3[2]]
    total_sum = array1_sum + array2_sum + array3_sum
    
    print(f'Array 1: {array1[element_list1[0]]} + {array1[element_list1[1]]} + {array1[element_list1[2]]} = {array1_sum}')
    print(f'Array 2: {array2[element_list2[0]]} + {array2[element_list2[1]]} + {array2[element_list2[2]]} = {array2_sum}')
    print(f'Array 3: {array3[element_list3[0]]} + {array3[element_list3[1]]} + {array3[element_list3[2]]} = {array3_sum}')
    print(f'Total sum: {total_sum}')

In [37]:
sum_of_arrays(array1,array2,array3)

Select an index # (0-9) from the first array: 3
Select an index # (0-9) from the first array: 8
Select an index # (0-9) from the first array: 4

Select an index # (0-9) from the second array: 9
Select an index # (0-9) from the second array: 7
Select an index # (0-9) from the second array: 1

Select an index # (0-9) from the third array: 3
Select an index # (0-9) from the third array: 6
Select an index # (0-9) from the third array: 5

Array 1: 37 + 99 + 43 = 179
Array 2: 99 + 23 + 54 = 176
Array 3: 79 + 25 + 94 = 198
Total sum: 553


In [38]:
array1,array2,array3

(array([ 5, 17, 70, 37, 43, 81, 98, 91, 99, 97]),
 array([21, 54, 48, 98, 98, 20, 12, 23, 52, 99]),
 array([85, 77, 17, 79, 97, 94, 25, 40, 89, 81]))